### PR TITLE
Remove xaptum prefix

### PR DESCRIPTION
**Pull request by drbild**
Removes xaptum prefix from
* library name
* build file variables
* test utilities
* readme project name

### CODE REVIEW

**Comment by drbild** [comment]
Rebased on latest master so CI passes.

**Comment by zanebeckwith** [comment]
I'm sorry, I just realized you put me as reviewer on this.

Should we scrub the XAPTUM_'s from the header guards, too?

**Comment by zanebeckwith** [comment]
Nice, LGTM

**Comment by drbild** [comment]
Good call! Fixed.  `grep -ri xaptum` now turns up clean (only copyright notices and travisci links remain).

**Comment by drbild** [comment]
FWIW, you'll probably be the final sign-off and merger for the foreseeable future!

**Pull request merged**
