### PR TITLE
Remove CPack packaging and use native CMake targets for deps

### PR DESCRIPTION
**Pull request by drbild**
This patch series

* removes the CPack config, since we're now using native packaging flows the distributions we support.
* imports dependencies as CMake targets, since the upstreams all now support that.
* cleans up the public/private designations on dependencies
* exports this library with full versioning and transitive dependency info for downstream CMake targets.

### CODE REVIEW

**Comment by drbild** [comment]
@zanebeckwith This should be ready for review now.

`install-amcl.sh` is pointing at a branch in my fork until milagro-crypto/milagro-crypto-c#249 is merged.   If you merge this now, I'lll submit a PR updating `install-amcl.sh` down the road.

**Comment by drbild** [comment]
@zanebeckwith Awesome, thanks!

Can we remove all the stuff in the "Build" section about building `xaptum-tpm`, `libsodium`, `AMCL`, etc.  Those should be procured by the user in the best way for their system (apt, homebrew, building from source, etc.), so it shouldn't be `ECDAA`'s job to instruct on how to do it.

**Comment by drbild** [comment]
I'll add some more changes and submit for re-review.

**Comment by zanebeckwith** [comment]
I removed the local build stuff, and moved `BUILD_EXAMPLES` into the cmake options matrix

**Comment by drbild** [comment]
LGTM

**Pull request merged**
