### PR TITLE
Add example programs

### LINKED ISSUE #12: Add example programs
Add example programs that, e.g., run the join process, sign, and verify.

These should be production-ready.

### PR DESCRIPTION
**Pull request by zanebeckwith**
closes #12

### CODE REVIEW

**Comment by zanebeckwith** [comment]
1) Good call. Done

2) Agreed. I was worried I was being too verbose as it was, and didn't want to repeat the usage messages from the binaries, but showing exactly how to run this so someone immediately gets going is a good idea. I'll add those tomorrow.

3) You mean in the `member_process_join_response` function? Yea, I now realize that's silly. I think it was from some strange idea in my head of simulating a network-based flow. Or something. Anyhow, I agree. It's exactly the same credential. Removed.

4) It doesn't regenerate it, it just checks that the issuer's public key was properly generated, then extracts the group public key from it. So, maybe something like `extract_group_public_key`?

**Comment by zanebeckwith** [comment]
J-play regarding point 2. I don't know why I thought that would take longer. I added some examples of the commands to the README.

**Comment by drbild** [comment]
LGTM.

It'd be nice to keep improving these going forward, eventually turning them into a one-stop shop for ECDAA, but like the `openssl` binary is for crypto and SSL. 

For instance, at some point it'd be nice to have a text-safe serialization format.

**Comment by zanebeckwith** [comment]
Yea, FIDO use a JSON-based text serialization, so at some point I'm planning on adding JSON-encoding to these, just to make interop with them easier.

And, agreed on continuing to improve these. Having a single executable that can run these as options (again, like `openssl` command) is the ultimate goal.

**Comment by zanebeckwith** [comment]
Thanks!

**Pull request merged**
